### ISSUE TITLE
Gesture Detector crashes on tap instead of dragging

### ISSUE THREAD

**Issue by Purukitto** [matthew-carroll/fluttery#12]
The Radial Gesture Detector crashes on tap.
Error log at tap:
`I/flutter (11659): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (11659): The following NoSuchMethodError was thrown during paint():
I/flutter (11659): The method 'toDouble' was called on null.
I/flutter (11659): Receiver: null
I/flutter (11659): Tried calling: toDouble()
I/flutter (11659):
I/flutter (11659): Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
I/flutter (11659): be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
I/flutter (11659):
I/flutter (11659): When the exception was thrown, this was the stack:
I/flutter (11659): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (11659): #1      double.* (dart:core-patch/double.dart:33:23)
I/flutter (11659): #2      RadialSeekBarPainter.paint (package:flox/components/RadialSeekBar.dart:208:34)
I/flutter (11659): #3      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:528:13)
I/flutter (11659): #4      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:571:7)
I/flutter (11659): #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #7      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (11659): #8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)I/flutter (11659): #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #13     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (11659): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)I/flutter (11659): #17     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1953:11)
I/flutter (11659): #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)I/flutter (11659): #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)I/flutter (11659): #24     RenderPointerListener.paint (package:flutter/src/rendering/proxy_box.dart:2669:11)
I/flutter (11659): #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)I/flutter (11659): #28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #30     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2501:15)
I/flutter (11659): #31     RenderFlex.paint (package:flutter/src/rendering/flex.dart:948:7)
I/flutter (11659): #32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #34     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2501:15)
I/flutter (11659): #35     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:361:5)
I/flutter (11659): #36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)I/flutter (11659): #39     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:548:11)
I/flutter (11659): #40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)I/flutter (11659): #43     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:369:12)
I/flutter (11659): #44     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1724:15)
I/flutter (11659): #45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)I/flutter (11659): #48     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (11659): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)I/flutter (11659): #51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2109:7)
I/flutter (11659): #52     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:127:11)
I/flutter (11659): #53     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter (11659): #54     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:876:29)
I/flutter (11659): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:348:19)
I/flutter (11659): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:702:13)
I/flutter (11659): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (11659): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
I/flutter (11659): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
I/flutter (11659): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
I/flutter (11659): #64     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (11659): #65     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (11659): (elided 3 frames from package dart:async)
I/flutter (11659):
I/flutter (11659): The following RenderObject was being processed when the exception was fired: RenderCustomPaint#37b79:
I/flutter (11659):   creator: CustomPaint ← Padding ← RadialSeekBar ← ConstrainedBox ← Container ← Center ← DecoratedBox
I/flutter (11659):     ← ConstrainedBox ← Container ← Listener ← _GestureSemantics ← RawGestureDetector ← ⋯
I/flutter (11659):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (11659):   constraints: BoxConstraints(w=200.0, h=200.0)
I/flutter (11659):   size: Size(200.0, 200.0)
I/flutter (11659): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (11659):     child: RenderPadding#eb069
I/flutter (11659):       child: RenderClipOval#ba9d3
I/flutter (11659):         child: RenderSemanticsAnnotations#7af7e
I/flutter (11659):           child: RenderImage#7fff0
I/flutter (11659): ════════════════════════════════════════════════════════════════════════════════════════════════════
`
Any help is appreciated :)

**Comment by Purukitto** [comment]
My thoughts are a simple return statement to make it quit running the DragUpdate() function if its a tap or something like that but being a beginner I'm not able to make out the exact issue or address it
