### ISSUE TITLE
OverlayBuilder and AnchoredOverlay not shown (only after rotating the screen)

### ISSUE THREAD

**Issue by sir-boformer** [matthew-carroll/fluttery#4]
I tried this with my own overlay, as well as the [official example](https://github.com/matthew-carroll/fluttery/blob/master/example/lib/example_layout_overlay.dart).

When I click on 'Show Overlay', the overlay is not shown. Only after rotating the screen, the overlay is visible. Hiding the overlay works, although there is a small delay (route animation?).

Flutter version: Latest master
Android Emulator API 26

**Comment by arnemolland** [comment]
I'm having the same problem, with the cause being that `markNeedsBuild` is being called during build. I'm dumping the exception here:

`E/flutter (29631): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (29631): setState() or markNeedsBuild() called during build.
E/flutter (29631): This _OverlayEntry widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (29631): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (29631):   _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#a5356](state: _OverlayEntryState#b5ca3)
E/flutter (29631): The widget which was currently being built when the offending call was made was:
E/flutter (29631):   OverlayBuilder(dirty, state: _OverlayBuilderState#fbbd6)
E/flutter (29631): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3485:11)
E/flutter (29631): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3511:6)
E/flutter (29631): #2      State.setState (package:flutter/src/widgets/framework.dart:1146:14)
E/flutter (29631): #3      _OverlayEntryState._markNeedsBuild (package:flutter/src/widgets/overlay.dart:174:5)
E/flutter (29631): #4      OverlayEntry.markNeedsBuild (package:flutter/src/widgets/overlay.dart:149:24)
E/flutter (29631): #5      _OverlayBuilderState.buildOverlay (package:fluttery/src/layout_overlays.dart:158:19)
E/flutter (29631): <asynchronous suspension>
E/flutter (29631): #6      _OverlayBuilderState.build (package:fluttery/src/layout_overlays.dart:163:5)
E/flutter (29631): #7      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
E/flutter (29631): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
E/flutter (29631): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (29631): #10     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
E/flutter (29631): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (29631): #12     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:118:18)
E/flutter (29631): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
E/flutter (29631): #14     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:107:11)
E/flutter (29631): #15     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
E/flutter (29631): #16     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
E/flutter (29631): #17     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
E/flutter (29631): #18     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:205:5)
E/flutter (29631): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
E/flutter (29631): #20     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
E/flutter (29631): #21     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
E/flutter (29631): #22     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
E/flutter (29631): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
E/flutter (29631): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
E/flutter (29631): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
E/flutter (29631): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
E/flutter (29631): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
E/flutter (29631): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&Sc
`
From my testing, the overlay is only displayed after rebuilding the widget tree or bullding another overlay.

**Comment by sergiuwd** [comment]
Guys, the fluttery package is not compatible with Dart 2, which you're most probably using.

**Comment by yash365** [comment]
> Remove the `fluttery` package from your dependencies and save this as a file instead, then import it in your old files that were using the `fluttery` package:
> 
> ```
> import 'package:flutter/material.dart';
> 
> class AnchoredOverlay extends StatelessWidget {
>   final bool showOverlay;
>   final Widget Function(BuildContext, Rect anchorBounds, Offset anchor) overlayBuilder;
>   final Widget child;
> 
>   AnchoredOverlay({
>     key,
>     this.showOverlay = false,
>     this.overlayBuilder,
>     this.child,
>   }) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Container(
>       // This LayoutBuilder gives us the opportunity to measure the above
>       // Container to calculate the "anchor" point at its center.
>       child: LayoutBuilder(
>         builder: (BuildContext context, BoxConstraints constraints) {
>           return OverlayBuilder(
>             showOverlay: showOverlay,
>             overlayBuilder: (BuildContext overlayContext) {
>               // To calculate the "anchor" point we grab the render box of
>               // our parent Container and then we find the center of that box.
>               RenderBox box = context.findRenderObject() as RenderBox;
>               final topLeft = box.size.topLeft(box.localToGlobal(const Offset(0.0, 0.0)));
>               final bottomRight = box.size.bottomRight(box.localToGlobal(const Offset(0.0, 0.0)));
>               final Rect anchorBounds = Rect.fromLTRB(
>                 topLeft.dx,
>                 topLeft.dy,
>                 bottomRight.dx,
>                 bottomRight.dy,
>               );
>               final anchorCenter = box.size.center(topLeft);
> 
>               return overlayBuilder(overlayContext, anchorBounds, anchorCenter);
>             },
>             child: child,
>           );
>         },
>       ),
>     );
>   }
> }
> 
> class OverlayBuilder extends StatefulWidget {
>   final bool showOverlay;
>   final Widget Function(BuildContext) overlayBuilder;
>   final Widget child;
> 
>   OverlayBuilder({
>     key,
>     this.showOverlay = false,
>     this.overlayBuilder,
>     this.child,
>   }) : super(key: key);
> 
>   @override
>   _OverlayBuilderState createState() => new _OverlayBuilderState();
> }
> 
> class _OverlayBuilderState extends State<OverlayBuilder> {
>   OverlayEntry overlayEntry;
> 
>   @override
>   void initState() {
>     super.initState();
> 
>     if (widget.showOverlay) {
>       WidgetsBinding.instance.addPostFrameCallback((_) => showOverlay());
>     }
>   }
> 
>   @override
>   void didUpdateWidget(OverlayBuilder oldWidget) {
>     super.didUpdateWidget(oldWidget);
>     WidgetsBinding.instance.addPostFrameCallback((_) => syncWidgetAndOverlay());
>   }
> 
>   @override
>   void reassemble() {
>     super.reassemble();
>     WidgetsBinding.instance.addPostFrameCallback((_) => syncWidgetAndOverlay());
>   }
> 
>   @override
>   void dispose() {
>     if (isShowingOverlay()) {
>       hideOverlay();
>     }
> 
>     super.dispose();
>   }
> 
>   bool isShowingOverlay() => overlayEntry != null;
> 
>   void showOverlay() {
>     if (overlayEntry == null) {
>       // Create the overlay.
>       overlayEntry = new OverlayEntry(
>         builder: widget.overlayBuilder,
>       );
>       addToOverlay(overlayEntry);
>     } else {
>       // Rebuild overlay.
>       WidgetsBinding.instance.addPostFrameCallback((_) => buildOverlay());
>     }
>   }
> 
>   void addToOverlay(OverlayEntry entry) async {
>     Overlay.of(context).insert(entry);
>   }
> 
>   void hideOverlay() {
>     if (overlayEntry != null) {
>       overlayEntry.remove();
>       overlayEntry = null;
>     }
>   }
> 
>   void syncWidgetAndOverlay() {
>     if (isShowingOverlay() && !widget.showOverlay) {
>       hideOverlay();
>     } else if (!isShowingOverlay() && widget.showOverlay) {
>       showOverlay();
>     }
>   }
> 
>   void buildOverlay() async {
>     overlayEntry?.markNeedsBuild();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     WidgetsBinding.instance.addPostFrameCallback((_) => buildOverlay());
> 
>     return widget.child;
>   }
> }
> 
> class CenterAbout extends StatelessWidget {
> 
>   final Offset position;
>   final Widget child;
> 
>   CenterAbout({
>     key,
>     this.position,
>     this.child,
>   }) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return new Positioned(
>       left: position.dx,
>       top: position.dy,
>       child: new FractionalTranslation(
>         translation: const Offset(-0.5, -0.5),
>         child: child,
>       ),
>     );
>   }
> }
> ```

where to add the file in these project

**Comment by MahdiPishguy** [comment]
@sergiuwd after removing 

```
  fluttery:
    path: ../
```

from `pubspec.yaml` thats into example directory i get more error

**Comment by Double-Are** [comment]
@MahdiPishguy I created another file called overlay. Pasted his code there while keeping the fluttery package installed. Referenced my own file, instead of importing fluttery/layout

If your files are small and modular enough, this shouldn't cause any problems moving forward.
