### ISSUE TITLE
AnchoredOverlay error Version0.08

### ISSUE THREAD

**Issue by MrReN** [matthew-carroll/fluttery#8]
[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 5684): setState() or markNeedsBuild() called during build.
This _OverlayEntry widget cannot be marked as needing to build because the framework is already in the process of building widgets.

**Comment by sgon00** [comment]
I got a similar error too when running the example app and click <Show Overlay> button:

```dart
E/flutter (29077): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: setState() or markNeedsBuild() called during build.
E/flutter (29077): This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (29077): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (29077):   Overlay-[LabeledGlobalKey<OverlayState>#37bc4](state: OverlayState#3bbe6(entries: [OverlayEntry#dd392(opaque: false; maintainState: false), OverlayEntry#4c4e4(opaque: false; maintainState: true), OverlayEntry#382da(opaque: true; maintainState: false), OverlayEntry#1e7a9(opaque: false; maintainState: true), OverlayEntry#9d170(opaque: false; maintainState: false)]))
E/flutter (29077): The widget which was currently being built when the offending call was made was:
E/flutter (29077):   LayoutBuilder(renderObject: _RenderLayoutBuilder#e1a19 relayoutBoundary=up2 NEEDS-LAYOUT)
E/flutter (29077): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3594:11)
E/flutter (29077): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3620:6)
E/flutter (29077): #2      State.setState (package:flutter/src/widgets/framework.dart:1143:14)
E/flutter (29077): #3      OverlayState.insert (package:flutter/src/widgets/overlay.dart:307:5)
E/flutter (29077): #4      _OverlayBuilderState.addToOverlay (package:fluttery/src/layout_overlays.dart:139:25)
E/flutter (29077): <asynchronous suspension>
E/flutter (29077): #5      _OverlayBuilderState.showOverlay (package:fluttery/src/layout_overlays.dart:131:7)
E/flutter (29077): #6      _OverlayBuilderState.syncWidgetAndOverlay (package:fluttery/src/layout_overlays.dart:153:7)
E/flutter (29077): #7      _OverlayBuilderState.didUpdateWidget (package:fluttery/src/layout_overlays.dart:105:5)
E/flutter (29077): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:3975:58)
E/flutter (29077): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
E/flutter (29077): #10     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:120:18)
E/flutter (29077): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2294:19)
E/flutter (29077): #12     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:109:11)
E/flutter (29077): #13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1716:58)
E/flutter (29077): #14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
E/flutter (29077): #15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1716:13)
E/flutter (29077): #16     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207:5)
E/flutter (29077): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter (29077): #18     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:805:17)
E/flutter (29077): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter (29077): #20     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
E/flutter (29077): #21     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
E/flutter (29077): #22     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
E/flutter (29077): #23     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
E/flutter (29077): #24     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1497:7)
E/flutter (29077): #25     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
E/flutter (29077): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
E/flutter (29077): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
E/flutter (29077): #28
```

**Comment by solnsumei** [comment]
I got the same error too
E/flutter (20723): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: setState() or markNeedsBuild() called during build.
E/flutter (20723): This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (20723): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (20723):   Overlay-[LabeledGlobalKey<OverlayState>#329f2](state: OverlayState#26de0(entries: [OverlayEntry#184fa(opaque: false; maintainState: false), OverlayEntry#d153f(opaque: false; maintainState: true), OverlayEntry#723ed(opaque: false; maintainState: false)]))
E/flutter (20723): The widget which was currently being built when the offending call was made was:
E/flutter (20723):   LayoutBuilder(renderObject: _RenderLayoutBuilder#54334 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT)
E/flutter (20723): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3594:11)
E/flutter (20723): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3620:6)
E/flutter (20723): #2      State.setState (package:flutter/src/widgets/framework.dart:1143:14)
E/flutter (20723): #3      OverlayState.insert (package:flutter/src/widgets/overlay.dart:307:5)
E/flutter (20723): #4      _OverlayBuilderState.addToOverlay (package:fluttery/src/layout_overlays.dart:139:25)
E/flutter (20723): <asynchronous suspension>
E/flutter (20723): #5      _OverlayBuilderState.showOverlay (package:fluttery/src/layout_overlays.dart:131:7)
E/flutter (20723): #6      _OverlayBuilderState.initState (package:fluttery/src/layout_overlays.dart:98:7)
E/flutter (20723): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3942:58)
E/flutter (20723): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
E/flutter (20723): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
E/flutter (20723): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
E/flutter (20723): #11     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:120:18)
E/flutter (20723): #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2294:19)
E/flutter (20723): #13     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:109:11)
E/flutter (20723): #14     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1716:58)
E/flutter (20723): #15     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
E/flutter (20723): #16     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1716:13)
E/flutter (20723): #17     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207:5)
E/flutter (20723): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter (20723): #19     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
E/flutter (20723): #20     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
E/flutter (20723): #21     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
E/flutter (20723): #22     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
E/flutter (20723): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter (20723): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (20723): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter (20723): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (20723): #27     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
E/flutter (20723): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter (20723): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (20723): #30     RenderOb

**Comment by hamedwaezi01** [comment]
I got it this problem while watching the `flutter challenge tinder matching' video .
I also tried the [(https://github.com/matthew-carroll/fluttery/pull/2#issuecomment-472237733)] solution but it fixed the problem of the first run. but I faced the same issue as I started dragging the card.(The card didn't move).

**Comment by mrjjwright** [comment]
Yes, I got the same issue.

**Comment by wenchangyiyo** [comment]
I've got the same message as below when I try to setState in onPanUpdate() or onPanEnd() functions:
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This _OverlayEntry widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#9340d](state: _OverlayEntryState#f3a44)
The widget which was currently being built when the offending call was made was:
  OverlayBuilder(dirty, state: _OverlayBuilderState#1c76b)
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3503:11)
#1      Element.markNeedsBuild (<…>

**Comment by RiaParshina** [comment]
same issue. Works with version 0.0.7 though
